1.Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [26]:
import numpy as np
x=np.arange(9)
print(x)
z=np.vander(x,3)
print("output should be like this..\n",z)

[0 1 2 3 4 5 6 7 8]
output should be like this..
 [[ 0  0  1]
 [ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]
 [36  6  1]
 [49  7  1]
 [64  8  1]]


In [28]:
def vandr(x1,n1):
    mat=np.zeros((len(x1),n1),dtype=int)
    for i in range(len(x1)):
        z=0
        for j in range(n1-1,-1,-1):
            mat[i][j]=x1[i]**z
            z=z+1
    print(mat)
vandr(x,3)

[[ 0  0  1]
 [ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]
 [36  6  1]
 [49  7  1]
 [64  8  1]]


In [19]:
help(np.vander)

Help on function vander in module numpy:

vander(x, N=None, increasing=False)
    Generate a Vandermonde matrix.
    
    The columns of the output matrix are powers of the input vector. The
    order of the powers is determined by the `increasing` boolean argument.
    Specifically, when `increasing` is False, the `i`-th output column is
    the input vector raised element-wise to the power of ``N - i - 1``. Such
    a matrix with a geometric progression in each row is named for Alexandre-
    Theophile Vandermonde.
    
    Parameters
    ----------
    x : array_like
        1-D input array.
    N : int, optional
        Number of columns in the output.  If `N` is not specified, a square
        array is returned (``N = len(x)``).
    increasing : bool, optional
        Order of the powers of the columns.  If True, the powers increase
        from left to right, if False (the default) they are reversed.
    
        .. versionadded:: 1.9.0
    
    Returns
    -------
    out : ndar

Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [39]:
l=np.array([3,5,7,2,8,10,11,65,72,81,99,100,150])
def func1(l1,k1):
    n=len(l1)
    for j in range(0,n-k1+1):
        y=(l1[j:j+k1].sum())/k1
        print(int(y))
func1(l,3)

5
4
5
6
9
28
49
72
84
93
116
